### ISSUE TITLE
Improve Wingpanel style, when window maximized

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#32] opened 2015-04-22 16:50 UTC
![ekraanipilt 2015-04-22 19 49 57](https://cloud.githubusercontent.com/assets/7373586/7280025/d0dc1a36-e928-11e4-8ef4-e2d872a914e0.png)

**Comment by TicTac7x** [comment] 2015-04-22 16:51
You can also see from the picure that maximized windows still have rounded corners, which is a bug.

**Comment by Defman21** [comment] 2015-04-22 17:02
Duplicate of #1

**Closed by Defman21** 2015-04-22 17:02 UTC

**Comment by TicTac7x** [comment] 2015-04-22 19:54
What about the rounded corners of the maximized window?

**Comment by Defman21** [comment] 2015-04-22 19:55
Cannot say anything about it. I'm waiting for an answer on reddit.
