### ISSUE TITLE
Weird gray box in tabs bar

### ISSUE THREAD

**Issue by TicTac7x** [eOS-themes/eXGTK#27] opened 2015-04-22 16:29 UTC
![ekraanipilt 2015-04-22 19 27 51](https://cloud.githubusercontent.com/assets/7373586/7279617/dbbef976-e925-11e4-8d9a-ef077d2b0f05.png)
![ekraanipilt 2015-04-22 19 29 23](https://cloud.githubusercontent.com/assets/7373586/7279627/e4bed172-e925-11e4-84a6-0ce312d46710.png)

Notice the little gray in the center of the image, in the tabs bar, this also happens in the Files for example.

**Comment by Defman21** [comment] 2015-04-22 16:32
Duplicate of #16

**Closed by Defman21** 2015-04-22 16:32 UTC
